name: Generate requirements.txt

on:
  push:
    branches: [ main ]
    paths: [ 'pyproject.toml' ]
  pull_request:
    branches: [ main ]
    paths: [ 'pyproject.toml' ]
  workflow_dispatch:

permissions:
  contents: write    

jobs:
  generate-requirements:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Generate requirements.txt
        run: uv pip compile pyproject.toml -o requirements.txt

      - name: Configure Git
        run: |
          git config --global user.name 'linduarte'
          git config --global user.email '140444382+linduarte@users.noreply.github.com'

      - name: Commit and push if changed
        run: |
          git add requirements.txt
          if git diff --staged --quiet; then
            echo "No changes to requirements.txt"
          else
            git commit -m "🤖 Auto-update requirements.txt from pyproject.toml"
            git push
          fi